<!doctype html><html lang=en><head><title>How to Capture the Exception Message From Assert.Throws in NUnit · Learn, Converse, Share
</title><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=color-scheme content="light dark"><meta name=author content="JM (Jason Meridth)"><meta name=description content='In the past I’ve used:
[ExpectedException(typeof(CustomException), ExpectedMessage="blah blah blah")] to set an exception expectation and assert on the message. With the recent releases of NUnit I’ve finally transitioned all my code to use:
Assert.Throws<CustomException>(() => someType.someMethod(someValue)); or
Assert.Throws<CustomException>(someType.someMethod); if the method has no parameters.
Only lately have I needed to capture the exception message and validate it. To do this you do the following:
var ex = Assert.Throws<CustomException>(() => someType.someMethod(someValue)); Assert.'><meta name=keywords content="jason meridth,meridth,jm,software developer"><meta name=fediverse:creator content><meta name=twitter:card content="summary"><meta name=twitter:title content="How to Capture the Exception Message From Assert.Throws in NUnit"><meta name=twitter:description content='In the past I’ve used:
[ExpectedException(typeof(CustomException), ExpectedMessage="blah blah blah")] to set an exception expectation and assert on the message. With the recent releases of NUnit I’ve finally transitioned all my code to use:
Assert.Throws<CustomException>(() => someType.someMethod(someValue)); or
Assert.Throws<CustomException>(someType.someMethod); if the method has no parameters.
Only lately have I needed to capture the exception message and validate it. To do this you do the following:
var ex = Assert.Throws<CustomException>(() => someType.someMethod(someValue)); Assert.'><meta property="og:url" content="http://jmeridth.com/posts/how-to-capture-exception-message-from-assert-throws-in-nunit/"><meta property="og:site_name" content="Learn, Converse, Share"><meta property="og:title" content="How to Capture the Exception Message From Assert.Throws in NUnit"><meta property="og:description" content='In the past I’ve used:
[ExpectedException(typeof(CustomException), ExpectedMessage="blah blah blah")] to set an exception expectation and assert on the message. With the recent releases of NUnit I’ve finally transitioned all my code to use:
Assert.Throws<CustomException>(() => someType.someMethod(someValue)); or
Assert.Throws<CustomException>(someType.someMethod); if the method has no parameters.
Only lately have I needed to capture the exception message and validate it. To do this you do the following:
var ex = Assert.Throws<CustomException>(() => someType.someMethod(someValue)); Assert.'><meta property="og:locale" content="en"><meta property="og:type" content="article"><meta property="article:section" content="posts"><meta property="article:published_time" content="2012-03-23T00:00:00-05:00"><meta property="article:modified_time" content="2012-03-23T00:00:00-05:00"><meta property="article:tag" content=".Net"><meta property="article:tag" content="Testing"><link rel=canonical href=http://jmeridth.com/posts/how-to-capture-exception-message-from-assert-throws-in-nunit/><link rel=preload href=/fonts/fa-brands-400.woff2 as=font type=font/woff2 crossorigin><link rel=preload href=/fonts/fa-regular-400.woff2 as=font type=font/woff2 crossorigin><link rel=preload href=/fonts/fa-solid-900.woff2 as=font type=font/woff2 crossorigin><link rel=stylesheet href=/css/coder.min.07092c1350ffd254998dc43a44ae96e617d14af4df4602626878df89189c5e1a.css integrity="sha256-BwksE1D/0lSZjcQ6RK6W5hfRSvTfRgJiaHjfiRicXho=" crossorigin=anonymous media=screen><link rel=stylesheet href=/css/coder-dark.min.a00e6364bacbc8266ad1cc81230774a1397198f8cfb7bcba29b7d6fcb54ce57f.css integrity="sha256-oA5jZLrLyCZq0cyBIwd0oTlxmPjPt7y6KbfW/LVM5X8=" crossorigin=anonymous media=screen><link rel=stylesheet href=/css/css_dark_mode_gist_embed_code.min.5f4f026828cc544c1497785bca628b4ddc8a6c1f154cc2b83c87a13ceaff419a.css integrity="sha256-X08CaCjMVEwUl3hbymKLTdyKbB8VTMK4PIehPOr/QZo=" crossorigin=anonymous media=screen><link rel=icon type=image/svg+xml href=/images/favicon.svg sizes=any><link rel=icon type=image/png href=/images/favicon-32x32.png sizes=32x32><link rel=icon type=image/png href=/images/favicon-16x16.png sizes=16x16><link rel=apple-touch-icon href=/images/apple-touch-icon.png><link rel=apple-touch-icon sizes=180x180 href=/images/apple-touch-icon.png><link rel=manifest href=/site.webmanifest><link rel=mask-icon href=/images/safari-pinned-tab.svg color=#5bbad5></head><body class="preload-transitions colorscheme-dark"><main class=wrapper><nav class=navigation><section class=container><a class=navigation-title href=http://jmeridth.com/>Learn, Converse, Share
</a><input type=checkbox id=menu-toggle>
<label class="menu-button float-right" for=menu-toggle><i class="fa-solid fa-bars fa-fw" aria-hidden=true></i></label><ul class=navigation-list><li class=navigation-item><a class=navigation-link href=/about/>About</a></li><li class=navigation-item><a class=navigation-link href=/posts/>Blog</a></li><li class=navigation-item><a class=navigation-link href=/tags/>Tags</a></li><li class=navigation-item><a class=navigation-link href=/projects/>Projects</a></li><li class=navigation-item><a class=navigation-link href=/contact/>Contact me</a></li></ul></section></nav><div class=content><section class="container post"><article><header><div class=post-title><h1 class=title><a class=title-link href=http://jmeridth.com/posts/how-to-capture-exception-message-from-assert-throws-in-nunit/>How to Capture the Exception Message From Assert.Throws in NUnit</a></h1></div><div class=post-meta><div class=date><span class=posted-on><i class="fa-solid fa-calendar" aria-hidden=true></i>
<time datetime=2012-03-23T00:00:00-05:00>March 23, 2012
</time></span><span class=reading-time><i class="fa-solid fa-clock" aria-hidden=true></i>
One-minute read</span></div><div class=tags><i class="fa-solid fa-tag" aria-hidden=true></i>
<span class=tag><a href=/tags/.net/>.Net</a>
</span><span class=separator>•</span>
<span class=tag><a href=/tags/testing/>Testing</a></span></div></div></header><div class=post-content><p>In the past I’ve used:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-csharp data-lang=csharp><span class=line><span class=cl><span class=na>[ExpectedException(typeof(CustomException), ExpectedMessage=&#34;blah blah blah&#34;)]</span>
</span></span></code></pre></div><p>to set an exception expectation and assert on the message. With the recent releases of NUnit I’ve finally transitioned all my code to use:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-csharp data-lang=csharp><span class=line><span class=cl><span class=n>Assert</span><span class=p>.</span><span class=n>Throws</span><span class=p>&lt;</span><span class=n>CustomException</span><span class=p>&gt;(()</span> <span class=p>=&gt;</span> <span class=n>someType</span><span class=p>.</span><span class=n>someMethod</span><span class=p>(</span><span class=n>someValue</span><span class=p>));</span>
</span></span></code></pre></div><p>or</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-csharp data-lang=csharp><span class=line><span class=cl><span class=n>Assert</span><span class=p>.</span><span class=n>Throws</span><span class=p>&lt;</span><span class=n>CustomException</span><span class=p>&gt;(</span><span class=n>someType</span><span class=p>.</span><span class=n>someMethod</span><span class=p>);</span>
</span></span></code></pre></div><p>if the method has no parameters.</p><p>Only lately have I needed to capture the exception message and validate it. To do this you do the following:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-csharp data-lang=csharp><span class=line><span class=cl><span class=kt>var</span> <span class=n>ex</span> <span class=p>=</span> <span class=n>Assert</span><span class=p>.</span><span class=n>Throws</span><span class=p>&lt;</span><span class=n>CustomException</span><span class=p>&gt;(()</span> <span class=p>=&gt;</span> <span class=n>someType</span><span class=p>.</span><span class=n>someMethod</span><span class=p>(</span><span class=n>someValue</span><span class=p>));</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=n>Assert</span><span class=p>.</span><span class=n>That</span><span class=p>(</span><span class=n>ex</span><span class=p>.</span><span class=n>Message</span><span class=p>,</span> <span class=n>Is</span><span class=p>.</span><span class=n>EqualTo</span><span class=p>(</span><span class=s>&#34;expected message here&#34;</span><span class=p>));</span>
</span></span></code></pre></div><p>I am blogging about this because I keep forgetting how to capture the exception message. Hope it helps someone else.</p></div><footer></footer></article></section></div><footer class=footer><section class=container>©
2007 -
2024
JM (Jason Meridth)
·
Powered by <a href=https://gohugo.io/ target=_blank rel=noopener>Hugo</a> & <a href=https://github.com/luizdepra/hugo-coder/ target=_blank rel=noopener>Coder</a>.</section></footer></main><script src=/js/coder.min.6ae284be93d2d19dad1f02b0039508d9aab3180a12a06dcc71b0b0ef7825a317.js integrity="sha256-auKEvpPS0Z2tHwKwA5UI2aqzGAoSoG3McbCw73gloxc="></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-4W46VMK7DQ"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-4W46VMK7DQ")</script></body></html>